#!/bin/bash

if [ -s /jd/config/crontab.list ] && [[ $(cat /jd/config/crontab.list) != $(crontab -l) ]]; then
    echo "[services.d] 检测到/jd/config/crontab.list有变化，立即刷新定时任务..."
    crontab /jd/config/crontab.list
fi
