#!/bin/bash

if [ -s /root/config/crontab.list ] && [[ $(cat /root/config/crontab.list) != $(crontab -l) ]]; then
    echo "[services.d] 检测到/root/config/crontab.list有变化，立即刷新定时任务..."
    crontab /root/config/crontab.list
fi
