#!/usr/bin/with-contenv bash

run_jup () {
    echo -e "\n======================== 更新源代码 ========================\n"
    update
}

run_jup 2>&1 | perl -pe "s|^(.+)|[cont-init.d] $(basename $0): \1|g"
