#!/usr/bin/with-contenv bash

run_config () {
    echo -e "\n======================== 检测配置文件 ========================\n"

    if [ ! -s $JD_DIR/config/crontab.list ]; then
        echo -e "检测到 $JD_DIR/config/crontab.list 不存在，从示例文件复制一份用于初始化...\n"
        cp -fv $JD_DIR/sample/crontab.sample.list $JD_DIR/config/crontab.list
        echo
    fi
    crontab $JD_DIR/config/crontab.list

    if [ ! -s $JD_DIR/config/config.sh ]; then
        echo -e "检测到 $JD_DIR/config/config.sh 不存在，从示例文件复制一份用于初始化...\n"
        cp -fv $JD_DIR/sample/config.sample.sh $JD_DIR/config/config.sh
        echo
    fi

    if [ ! -f $JD_DIR/log/.tmp/scripts.list.old ]; then
        cp -fv $JD_DIR/sample/scripts.list.old $JD_DIR/log/.tmp/
    fi
}

run_config 2>&1 | perl -pe "s|^(.+)|[cont-init.d] $(basename $0): \1|g"
